language: java
bundler_args: --retry 1

services:
  - docker
  
before_install:
  - docker build -t r2cloud ./Dockerbuild
  - docker run r2cloud

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)