language: java
bundler_args: --retry 1

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -f $HOME/.m2/repository/ru/r2cloud/
  
services:
  - docker
  
script:
  - mvn cobertura:cobertura
  - cp ./target/*.deb ./target/it-tests
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build -t r2cloud ./target/it-tests
  - docker run --privileged=true --name r2cloud -d --tty r2cloud
  - docker exec r2cloud /home/pi/r2cloud/bin/start-tests.sh
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
