language: java
bundler_args: --retry 1

services:
  - docker
  
script:
  - mvn cobertura:cobertura
  - cp ./target/*.deb ./Dockerbuild
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build -t r2cloud ./Dockerbuild
  - docker run r2cloud
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
