language: java
bundler_args: --retry 2

cache:
  directories:
  - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

services:
  - docker

before_install:
  - gem install package_cloud
    
script:
  - set -e
  - mvn cobertura:cobertura
  - cp ./target/*.deb ./target/it-tests
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker build -t r2cloud ./target/it-tests
  - docker run --privileged=true --name r2cloud -d --tty r2cloud
  - docker exec r2cloud /home/pi/r2cloud/bin/start-tests.sh
  - package_cloud push dernasherbrezon/r2cloud/raspbian/stretch target/*.deb
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
